#!/bin/bash

###Check that only root can run this script###
if [ $(id -u) -eq 0 ]
then 


menu=$(whiptail --title "Main Menu" --menu "Choose an option" 25 78 16 \
"Add User" "Add a user to the system" \
"List Users" "List all users on the system" \
"Delete User" "Delete an existing user" \
"Modify User" "Modify an existing user" \
"Enable User" "Unlock the user account" \
"Disable User" "Lock the user account" \
"Change Password" "Change Password of an existing user" \
"Add Group" "Add a user group to the system" \
"List Groups" "List all groups on the system" \
"Delete Group" "Delete an existing group" \
"About" "Some information about this tool and the author" 3>&1 1>&2 2>&3)


case $menu in

  "Add User") ./scripts/adduser ;;
  "List Users") ./scripts/listusers ;;
  "Delete User") ./scripts/deleteuser ;;
  "Modify User") ./scripts/modifyuser ;;
  "Enable User") ./scripts/enableuser ;;
  "Disable User") ./scripts/disableuser ;;
  "Change Password") ./scripts/changepassword ;;
  "Add Group") ./scripts/addgroup ;;
  "List Groups") ./scripts/listgroups ;;
  "Delete Group") ./scripts/deletegroup ;;
  "About") ./scripts/about ;;

esac




else
whiptail --title "ALERT" --msgbox "Sorry Only Root Can Run This Script :(" 8 78

fi
